### ISSUE TITLE
Solve Round A

### ISSUE THREAD

**Issue by lostgirljourney** [BlankCoders/GoogleKickStart2020_Solutions#3]
### Solve Questions of Round A

Languages accepted:
 - C
 - C++
 - Java
 - Python

Questions to view: <https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/Round%20A/QuestionsList.md>

**Important: Comment below to let us know what you want to solve & in which language. 😄**

Assignees:
* Allocation ✅
  - C - @hazard4king 
  - C++ - @pixan198 
  - Java - @evandrix 
  - Python - @lostgirljourney 

* Plates ✅
  - C - @ighosh98 
  - C++ - @pixan198 
  - Java - @amith-gowda 
  - Python - @hritik5102 

* Workout ✅
  - C - @ighosh98 
  - C++ - @pixan198 
  - Java - @xenoteo 
  - Python - @drishtantR1508

* Bundling
  - C - NA
  - C++ - @pixan198 - **Completed**
  - Java - @xenoteo - **Completed**
  - Python - @imsushant12 - **Completed**

**NA  - Not Assigned**

🚀 Happy Coding 🚀

**Comment by pixan198** [comment]
Hey @lostgirljourney , I want to work on this issue!

**Comment by lostgirljourney** [comment]
> Hey @lostgirljourney , I want to work on this issue!

@pixan198 question & language; mention it.

**Comment by pixan198** [comment]
@lostgirljourney 

Language:
- C++

Questions:
- Allocation
- Plates

**Comment by pixan198** [comment]
Hey @lostgirljourney , I'd like to work on
Language:
- C++

Questions:
- Workout
- Bundling

**Comment by lostgirljourney** [comment]
Okay you can go ahead but please add your own codes. Don't just do for Hacktoberfest. :hugs: @pixan198

**Comment by pixan198** [comment]
@lostgirljourney Yeah

**Comment by evandrix** [comment]
Hey @lostgirljourney , I'd like to work on
Language:

- C++

Questions:

- Allocation

**Comment by lostgirljourney** [comment]
@evandrix alright assigning you.

**Comment by hazard4king** [comment]
Hi! @lostgirljourney 
 I'd like to work on
Language:
C
Question:
Allocation

**Comment by lostgirljourney** [comment]
@hazard4king assigning you.

**Comment by ighosh98** [comment]
Hi,
I'd like to work on the following:
Language: C
Problem: Plates

**Comment by Sweta040799** [comment]
I would like to solve the issues
Language: C++
Problems:
-> Allocation 
-> Bundling

**Comment by lostgirljourney** [comment]
@Sweta040799 assigning you.

**Comment by lostgirljourney** [comment]
@Sweta040799 that's already assigned!

**Comment by lostgirljourney** [comment]
@ighosh98 assigning you.

**Comment by Sweta040799** [comment]
Can I change the language to C for problem: Bundling

**Comment by lostgirljourney** [comment]
@Sweta040799 assigning you!

**Comment by ighosh98** [comment]
@lostgirljourney please review #28

**Comment by Anni852** [comment]
Assigning you @ighosh98

**Comment by amith-gowda** [comment]
Hey, I'd like to work on the plates problem in Java

**Comment by lostgirljourney** [comment]
@amith-gowda assigning you.

**Comment by shr3ysavage** [comment]
Will be pushing a cleaner and slightly more efficient solution for Allocation in C++

**Comment by hritik5102** [comment]
Hello @lostgirljourney , I would like to contribute to this issue 

**Round** - A
**Problem** - Plates
**Language** - Python

Thank you :)

**Comment by lostgirljourney** [comment]
> Hello @lostgirljourney , I would like to contribute to this issue 
> 
> **Round** - A
> **Problem** - Plates
> **Language** - Python
> 
> Thank you :)

@hritik5102 assigning you.

**Comment by hritik5102** [comment]
Hello @lostgirljourney , Please check PR #52 

If any changes required please let me know
Thank you :)

**Comment by drishtantR1508** [comment]
I want to contribute on workout problem round A in python language.

@Anni852 
@lostgirljourney

**Comment by Anni852** [comment]
Assigned @drishtantR1508

**Comment by xenoteo** [comment]
Hello @lostgirljourney, I would like to contribute on workout in Java

**Comment by lostgirljourney** [comment]
@xenoteo sure, assigned.

**Comment by xenoteo** [comment]
I would like to contribute on Bundling in Java as well :)

**Comment by OctoplusNinja** [comment]
Assigned you @xenoteo.

**Comment by Ankit-2312** [comment]
Hey, I'd like to work on the Allocation problem in C++

**Comment by lostgirljourney** [comment]
> Hey, I'd like to work on the Allocation problem in C++

Hey, allocation is already done in CPP.
If you like to contribute check out other issues.
🚀

**Comment by imsushant12** [comment]
Hey @lostgirljourney , I would like to contribute to this issue:-

Round - A.
Problem - Bundling.
Language - Python.

**Comment by lostgirljourney** [comment]
@imsushant12 assigning you.
