### ISSUE TITLE
Solve Round E

### ISSUE THREAD

**Issue by lostgirljourney** [BlankCoders/GoogleKickStart2020_Solutions#4]
### Solve Questions of Round E

Languages accepted:
 - C
 - C++
 - Java
 - Python

Questions to view: <https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/Round%20E/QuestionsList.md>

**Important: Comment below to let us know what you want to solve & in which language. 😄**

Assignees:
* Longest Arithmetic ✅
  - C - @shikharmehrotra
  - C++ - @OctoplusNinja
  - Java - @kpx3 
  - Python - @drishtantR1508

* High Buildings ✅
  - C - @shikharmehrotra 
  - C++ - @abhinashgiri 
  - Java - @imsushant12 
  - Python - @drishtantR1508 

* Toys
  - C - NA
  - C++ - @GoGi2712 - **Completed**
  - Java - @developerayuva
  - Python - @drishtantR1508 - **Completed**

* Golden Stone
  - C - NA
  - C++ - @drishtantR1508 - **Completed**
  - Java - @sleepyboyskm 
  - Python - @drishtantR1508 - **Completed**

**NA  - Not Assigned**

🚀 Happy Coding 🚀

**Comment by abhinashgiri** [comment]
I want to work on High Buildings. Please assign me

**Comment by lostgirljourney** [comment]
@abhinashgiri assigning you.

**Comment by GoGi2712** [comment]
@lostgirljourney  Hey! I want to work on Toys in C++. Please assign me

**Comment by lostgirljourney** [comment]
@GoGi2712 alright assigning you.

**Comment by snowden-007** [comment]
@lostgirljourney @Anni852  i want to do Longest arithmetic in C language

**Comment by snowden-007** [comment]
I want to do high building in C lanuage 
@Anni852 
@lostgirljourney

**Comment by lostgirljourney** [comment]
@snowden-007 assigned

**Comment by drishtantR1508** [comment]
I want to do contribution on high building  problem in python lanuage.
@Anni852
@lostgirljourney

**Comment by drishtantR1508** [comment]
I want to do contribution on longest arithmetic  problem in python.
@Anni852
@lostgirljourney

**Comment by Anni852** [comment]
Alright assigning you @drishtantR1508

**Comment by kpx3** [comment]
hello i would like like to work on longest arithmetic in java

**Comment by lostgirljourney** [comment]
Alright @kpx3 assigned

**Comment by drishtantR1508** [comment]
I want to do contribution on toys problem in python.
@Anni852
@lostgirljourney_

**Comment by lostgirljourney** [comment]
@drishtantR1508 assigned.

**Comment by paslucena** [comment]
Hi, I want to try the Golden Stone in Python, please!

**Comment by lostgirljourney** [comment]
@paslucena assigned!

**Comment by lostgirljourney** [comment]
@imsushant12 assigned 🚀

**Comment by developerayuva** [comment]
Hi @lostgirljourney  @OctoplusNinja
Can I work on Toys in Java?

**Comment by sleepyboyskm** [comment]
Hi @lostgirljourney! Please assign me Golden Stone solution using Java :)

**Comment by Devolious** [comment]
Please assign me Toys Solution using Java @lostgirljourney !

**Comment by sleepyboyskm** [comment]
Please assign me to solve Toys problem using Java :)

**Comment by sleepyboyskm** [comment]
Hi @lostgirljourney @OctoplusNinja I have made a pull request regarding Java solution for Golden stone solution, please merge it asap :))

**Comment by lostgirljourney** [comment]
@sleepyboyskm okay, go ahead.

**Comment by lostgirljourney** [comment]
@developerayuva go ahead.

**Comment by sleepyboyskm** [comment]
@lostgirljourney Please assign me Java solution of Golden Stone problem. :)
