### ISSUE TITLE
Solve Round F

### ISSUE THREAD

**Issue by lostgirljourney** [BlankCoders/GoogleKickStart2020_Solutions#5]
### Solve Questions of Round F

Languages accepted:
 - C
 - C++
 - Java
 - Python

Questions to view: <https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/Round%20F/QuestionsList.md>

**Important: Comment below to let us know what you want to solve & in which language. 😄**

Assignees:
* ATM Queue
  - C - @Krish03na 
  - C++ - @abhinashgiri - **Completed**
  - Java - @imsushant12 - **Completed**
  - Python - @paslucena - **Completed**

* Metal Harvest
  - C - NA
  - C++ - @praj1wal - **Completed**
  - Java - NA 
  - Python - @lokendra1704 - **Completed**

* Painters' Duel
  - C - NA
  - C++ - @dumbbutgenius - **Completed**
  - Java - NA
  - Python - NA 

* Yeetzhee
  - C - NA
  - C++ - @Devolious 
  - Java - NA
  - Python - @sid-khuntwal - **Completed**

**NA  - Not Assigned**

🚀 Happy Coding 🚀

**Comment by paslucena** [comment]
Hi! I'd like to try the ATM Queue in Python, please.

**Comment by lostgirljourney** [comment]
@paslucena assigning you!

**Comment by abhinashgiri** [comment]
I want to solve all these questions in C++. I have been doing cp for a long time. Please assign me .

**Comment by praj1wal** [comment]
Metal harvest, C++. Please assign.

**Comment by lostgirljourney** [comment]
@praj1wal assigning you!

**Comment by lokendra1704** [comment]
Hey I'd like to try Metal Harvest, Python

**Comment by lostgirljourney** [comment]
@lokendra1704 assigning you!

**Comment by snowden-007** [comment]
I want to do ATM queue in C
@lostgirljourney 
@Anni852

**Comment by lostgirljourney** [comment]
@snowden-007 assigned

**Comment by shr3ysavage** [comment]
Painter's Duel in C++

**Comment by lostgirljourney** [comment]
@shr3ysavage assigned!

**Comment by sid-khuntwal** [comment]
Hey I have solved Yeetzhee problem using python. May I contribute? Please assign me!

**Comment by lostgirljourney** [comment]
@sid-khuntwal assigning you!

**Comment by sid-khuntwal** [comment]
@lostgirljourney Created the PR please have a look.

**Comment by OctoplusNinja** [comment]
@sid-khuntwal merged your PR. 🚀

**Comment by lordgavy01** [comment]
Hi, Can I work on ATM Queue in C?

**Comment by lostgirljourney** [comment]
@lordgavy01 assigned

**Comment by Devolious** [comment]
I want to solve yetzhee cpp solution. @lostgirljourney Please assign me.

**Comment by Devolious** [comment]
I want to solve Yetzhee problem using CPP. @lostgirljourney @OctoplusNinja Please assign me.

**Comment by OctoplusNinja** [comment]
Assigned @Devolious 🚀

**Comment by Krish03na** [comment]
Hi @lostgirljourney, could you please assign me ATM Queue in C? Thanks

**Comment by lostgirljourney** [comment]
okayy @Krish03na :)

**Comment by Krish03na** [comment]
I think you forgot to assign @lostgirljourney

**Comment by lostgirljourney** [comment]
@Krish03na you can work on it. Go ahead. I'm travelling. Not active for a while.

**Comment by Krish03na** [comment]
Sure! NP @lostgirljourney

**Comment by Devesh-coder** [comment]
@lostgirljourney I would like to work on Metal Harvest in java!

**Comment by lostgirljourney** [comment]
go ahead @Devesh-coder :rocket:

**Comment by Krish03na** [comment]
Please assign me Metal Harvest in C @lostgirljourney
