### ISSUE TITLE
Solve Round B

### ISSUE THREAD

**Issue by lostgirljourney** [BlankCoders/GoogleKickStart2020_Solutions#6]
### Solve Questions of Round B

Languages accepted:
 - C
 - C++
 - Java
 - Python

Questions to view: <https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/Round%20B/QuestionsList.md>

**Important: Comment below to let us know what you want to solve & in which language. 😄**

Assignees:
* Bike Tour ✅
  - C - @snowden-007 
  - C++ - @trivediavinash
  - Java - @adhi-2311
  - Python - @niranjantuty 

* Bus Routes ✅
  - C - @deetav 
  - C++ - @imsushant12   
  - Java - @imsushant12 
  - Python - @dumbbutgenius

* Robot Path Decoding
  - C - NA
  - C++ - @vanjo9800 - **Completed**
  - Java - @vanjo9800 - **Completed**
  - Python - NA 

* Wandering Robot
  - C - NA
  - C++ - @deetav
  - Java - NA 
  - Python - @Devolious - **Completed**

**NA  - Not Assigned**

🚀 Happy Coding 🚀

**Comment by trivediavinash** [comment]
@lostgirljourney  I want to work on Bike tour problem in C++ language .Please assign me

**Comment by lostgirljourney** [comment]
@trivediavinash assigning you!

**Comment by Sweta040799** [comment]
I would like to solve problem
Language: C++
problem : Bus Routes

**Comment by lostgirljourney** [comment]
@Sweta040799 assigning you

**Comment by shr3ysavage** [comment]
I'd like to push a cleaner solution to Bike Tour in C++

**Comment by shr3ysavage** [comment]
I'd like to push the solution for Bus Routes in C++

**Comment by shr3ysavage** [comment]
I'd like to push the solution for Bus Routes in Python

**Comment by Anni852** [comment]
assigning you @shr3ysavage

**Comment by niranjantuty** [comment]
@lostgirljourney @Anni852 I would like to do Bike Tour in Python.

**Comment by lostgirljourney** [comment]
@niranjantuty okay assigning you.

**Comment by snowden-007** [comment]
@lostgirljourney @Anni852 
I would like to do Bike Tour in C programming language.
Can you assign it to me?

**Comment by Anni852** [comment]
Okay Assigned you @snowden-007

**Comment by vanjo9800** [comment]
@lostgirljourney I want to work on Robot Path Decoding with C++ and Java implementations. Can you assign it to me?

**Comment by lostgirljourney** [comment]
@vanjo9800 assigned!

**Comment by adhi-2311** [comment]
Hi @lostgirljourney I would love to add my java solution to Bike Tour.

**Comment by lostgirljourney** [comment]
@adhi-2311 assigned!

**Comment by imsushant12** [comment]
Hi, @lostgirljourney , Can I work on issue:

Bus Routes in C++ ?

**Comment by OctoplusNinja** [comment]
Assigned you @imsushant12 🚀

**Comment by imsushant12** [comment]
Hi, Can I work on issue:

Bus Routes Solution in JAVA?

**Comment by lostgirljourney** [comment]
@imsushant12 sure

**Comment by lostgirljourney** [comment]
@imsushant12 assigned! 🚀

**Comment by lostgirljourney** [comment]
@deetav assigned

**Comment by Devolious** [comment]
@lostgirljourney Hello! I would like to work on the Wandering Robot problem using Python. Can you please assign me?

**Comment by lostgirljourney** [comment]
@Devolious assigned.

**Comment by deetav** [comment]
Hi ! I would love to add my C++ solution to the problem Wandering Robot. Kindly assign me :)

**Comment by lostgirljourney** [comment]
@deetav go ahead

**Comment by Nat-chan256** [comment]
@lostgirljourney Hello! I would like to add solution of "Wandering Robot" problem in Java.

**Comment by lostgirljourney** [comment]
go ahead @Nat-chan256
