### ISSUE TITLE
Solve Round D

### ISSUE THREAD

**Issue by lostgirljourney** [BlankCoders/GoogleKickStart2020_Solutions#7]
### Solve Questions of Round D

Languages accepted:
 - C
 - C++
 - Java
 - Python

Questions to view: <https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/Round%20D/QuestionsList.md>

**Important: Comment below to let us know what you want to solve & in which language. 😄**

Assignees:
* Record Breaker ✅
  - C - @adhi-2311
  - C++ - @ayerhs7 
  - Java - @kpx3
  - Python - @paslucena 

* Alien Piano
  - C - @Krish03na
  - C++ - @imsushant12 - **Completed**
  - Java - @imsushant12 - **Completed**
  - Python - NA

* Beauty of tree
  - C - NA
  - C++ - @ayerhs7 - **Completed**
  - Java - NA
  - Python - NA 

* Locked Doors
  - C - NA
  - C++ - NA
  - Java - @sleepyboyskm
  - Python - NA

**NA  - Not Assigned**

🚀 Happy Coding 🚀

**Comment by ayerhs7** [comment]
Hey! I would like to solve the first three problems Record Breaker, Alien piano and beauty of tree. All three in C++. Please reply asap!

**Comment by lostgirljourney** [comment]
@ayerhs7 yeah assigning you.

**Comment by paslucena** [comment]
Hey, I'm going to try the Record Breaker in python, if it's ok!

**Comment by AnshMishra2001** [comment]
Pls assign this task to me. I would love to slove as many problems as I can

**Comment by lostgirljourney** [comment]
@AnshMishra2001 sorry i can't assign you entire issue you've to mention the language & problem for which you would like to solve.

**Comment by kpx3** [comment]
hello i would like to contribute to record breaker in java

**Comment by lostgirljourney** [comment]
@kpx3 assigned

**Comment by adhi-2311** [comment]
Hi @lostgirljourney I would love to add my C solution to Record Breaker Problem.

**Comment by lostgirljourney** [comment]
@adhi-2311 assigned!

**Comment by AdityaGarg190** [comment]
Hi! can i work on Alien Piano in C.

**Comment by Devolious** [comment]
@lostgirljourney @adhi-2311  Please assign me solving the question Locked Doors using CPP language.

**Comment by lostgirljourney** [comment]
@Devolious Is #5 done?

**Comment by Devolious** [comment]
@lostgirljourney I have made a pull request for #5 please review and merge it.

**Comment by lostgirljourney** [comment]
@Devolious assigned 🤖

**Comment by Krish03na** [comment]
Hi @lostgirljourney, could you please assign me alien piano in C? Thanks

**Comment by lostgirljourney** [comment]
ohkay @Krish03na :)

**Comment by sleepyboyskm** [comment]
@lostgirljourney I would like to solve Round-D Locked Doors using Java. Please assign it to me.

**Comment by lostgirljourney** [comment]
@sleepyboyskm assigned. 🚀

**Comment by sleepyboyskm** [comment]
@lostgirljourney I have made pull request for Locked doors java solution please merge it and please assign me the C++ solution to Locked Doors too. :)

**Comment by lostgirljourney** [comment]
@sleepyboyskm okay. go ahead.

**Comment by sleepyboyskm** [comment]
@lostgirljourney Please merge the previous pull request :)

**Comment by sleepyboyskm** [comment]
@lostgirljourney I have made a pull request for Locked Doors CPP solution adhering to guidelines. Please merge my pull request :)

**Comment by rk1091** [comment]
Hi @lostgirljourney
I'd like to solve Alien Piano and Beauty of Tree both in Python and Locked Doors in both C++ and Python
Kindly assign the problems to me.
Thanks :)
