### ISSUE TITLE
Solve Round G

### ISSUE THREAD

**Issue by lostgirljourney** [BlankCoders/GoogleKickStart2020_Solutions#73]
### Solve Questions of Round G

Languages accepted:
 - C
 - C++
 - Java
 - Python

Questions to view: <https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/Round%20G/QuestionsList.md>

**Important: Comment below to let us know what you want to solve & in which language. 😄**

Assignees:
* Kick_Start ✅
  - C - @maityankan10 
  - C++ - @drishtantR1508
  - Java - @adhi-2311
  - Python - @drishtantR1508

* Maximum Coins ✅
  - C - @deetav
  - C++ - @dumbbutgenius 
  - Java - @kpx3
  - Python - @mohinesh9999

* Combination Lock
  - C - @deetav - **Completed**
  - C++ - @sakshiseth - **Completed**
  - Java - @Ratheshan03
  - Python - @Ratheshan03

* Merge Cards
  - C - NA
  - C++ - @sakshiseth - **Completed**
  - Java - NA
  - Python - @drishtantR1508 - **Completed**

**NA  - Not Assigned**

🚀 Happy Coding 🚀

**Comment by drishtantR1508** [comment]
It want to contribute in round g Kickstart problem in c++.

**Comment by drishtantR1508** [comment]
I want to contribute on round g Kickstart problem in python also.
@Anni852 
@lostgirljourney

**Comment by lostgirljourney** [comment]
@drishtantR1508 assigned.

**Comment by lostgirljourney** [comment]
@drishtantR1508 can you specify problem.

**Comment by mohinesh9999** [comment]
i want to contribute kicstart and maximum coins in python

**Comment by lostgirljourney** [comment]
@mohinesh9999 assigned!

**Comment by drishtantR1508** [comment]
i want to contribute on kickstart problem in c++ and python too...
@Anni852 @lostgirljourney

**Comment by drishtantR1508** [comment]
> @drishtantR1508 can you specify problem?

I have already mentioned kickstart problem in my earlier comment.

**Comment by lostgirljourney** [comment]
Ohkay got it. Sorry! 😅

Alright @drishtantR1508 assigned.

**Comment by lostgirljourney** [comment]
> i want to contribute kicstart and maximum coins in python

@mohinesh9999 assigning maximum as kickstart already assigned.

**Comment by drishtantR1508** [comment]
Can you please confirm on which language I am Assigned because I had previously asked for Kick_Start problem in C++ As well as python🙂

**Comment by drishtantR1508** [comment]
Oh i got it , thanks!🙂

**Comment by lostgirljourney** [comment]
> Can you please confirm on which language I am Assigned because I had previously asked for Kick_Start problem in C++ As well as python

Heyy do it in both since it was you at first asking for it.

**Comment by kpx3** [comment]
hello i would like to work maximum coin question in java

**Comment by lostgirljourney** [comment]
@kpx3 assigned.

**Comment by snowden-007** [comment]
I want to do maximum coins and kickstart in C language

**Comment by adhi-2311** [comment]
Hi, i would love to add my java solution to Round G kick_start problem @lostgirljourney

**Comment by maityankan10** [comment]
please assign kickstart to me for C LANGUAGE

**Comment by lostgirljourney** [comment]
@maityankan10 & @adhi-2311 assigned

**Comment by sakshiseth** [comment]
@lostgirljourney Please assign C++ Merge Cards or combination lock to me. If possible please assign both.

**Comment by lostgirljourney** [comment]
@sakshiseth assigned both!

**Comment by sosavle** [comment]
I'd like to solve Combination Lock in Python, if possible :)

**Comment by lostgirljourney** [comment]
> I'd like to solve Combination Lock in Python, if possible :)

@sosavle assigned!

**Comment by shr3ysavage** [comment]
I'll be needing confirmation to submit solution of combination lock in Python

**Comment by shr3ysavage** [comment]
I'll be needing confirmation to submit solution of maximum coins in C++

**Comment by lostgirljourney** [comment]
@shr3ysavage alright assigned!

**Comment by lostgirljourney** [comment]
> I'll be needing confirmation to submit solution of combination lock in Python

It's already assigned. 😄

**Comment by drishtantR1508** [comment]
Hey @lostgirljourney  and @Anni852 I would like to contribute on merge card problem in python.

**Comment by maityankan10** [comment]
assign combinational lock to me in c

**Comment by lostgirljourney** [comment]
@maityankan10 assigned!

**Comment by drishtantR1508** [comment]
what will be the issue no for the merge card problem in python

**Comment by lostgirljourney** [comment]
@drishtantR1508 issue no. #73

**Comment by drishtantR1508** [comment]
ohk :)

**Comment by lostgirljourney** [comment]
@deetav assigned :rocket:

**Comment by Ratheshan03** [comment]
Hi @lostgirljourney  I would like to solve Combination Lock in Java and Python. 
Will you be able to assign me ? 
Thankyou.

**Comment by lostgirljourney** [comment]
@Ratheshan03 assigned!
