### ISSUE TITLE
Solve Round C

### ISSUE THREAD

**Issue by OctoplusNinja** [BlankCoders/GoogleKickStart2020_Solutions#8]
### Solve Questions of Round C

Languages accepted:
 - C
 - C++
 - Java
 - Python

Questions to view: <https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/Round%20C/QuestionsList.md>

**Important: Comment below to let us know what you want to solve & in which language. 😄**

Assignees:
* Countdown ✅
  - C - @hemangdtu
  - C++ - @AndreiG23
  - Java - @kpx3
  - Python - @niranjantuty

* Stable Wall
  - C - NA
  - C++ - @dumbbutgenius - **Completed**
  - Java - @imsushant12 - **Completed**
  - Python - @drishtantR1508 

* Perfect Subarray
  - C - @deetav 
  - C++ - @abhinashgiri - **Completed**
  - Java - @Tiwarisonal19 
  - Python - NA 

* Candies
  - C - NA 
  - C++ - @vishalram14
  - Java - NA
  - Python - NA

**NA  - Not Assigned**

🚀 Happy Coding 🚀

**Comment by AndreiG23** [comment]
I want to solve Countdown in C++

**Comment by lostgirljourney** [comment]
> I want to solve Countdown in C++

assigning you! @AndreiG23

**Comment by abhinashgiri** [comment]
I want to work on the Perfect Subarray in CPP. Please assign me

**Comment by lostgirljourney** [comment]
@abhinashgiri assigning you.

**Comment by hemangdtu** [comment]
Hello, I want to solve Countdown Problem in C. Please assign me.

**Comment by lostgirljourney** [comment]
@hemangdtu assigning you.

**Comment by niranjantuty** [comment]
I would like to work on the Countdown problem in Python.

**Comment by Anni852** [comment]
@niranjantuty Assigning you.

**Comment by shr3ysavage** [comment]
I'd like to push a solution for Stable Wall in C++

**Comment by Anni852** [comment]
Alright, assigning you @shr3ysavage

**Comment by kpx3** [comment]
hello i would like to take up countdown problem in java

**Comment by Anni852** [comment]
assigned @kpx3  !

**Comment by BananaMoshpit** [comment]
Hi, could I get Candies in C?

**Comment by lostgirljourney** [comment]
@BananaMoshpit assigned...

**Comment by imsushant12** [comment]
Hey, I would like to work on Stable Wall, in Java

**Comment by lostgirljourney** [comment]
@imsushant12 assigning you.

**Comment by vishalram14** [comment]
Would like to solve candies C++

**Comment by lostgirljourney** [comment]
@vishalram14 assigning you

**Comment by Tiwarisonal19** [comment]
I would like to work on Perfect Subarray in Java.

**Comment by drishtantR1508** [comment]
I would like to work on Stable wall problem in python. Please assign me!

**Comment by deetav** [comment]
Hi! I would love to add my C code to the Perfect Subarray problem. Please assign me :)

**Comment by OctoplusNinja** [comment]
Assigned you @deetav

**Comment by Yasir-Mohi-ud-din** [comment]
I would like to push my solution for the countdown problem in  the C  language.

**Comment by OctoplusNinja** [comment]
Hi @Yasir-Mohi-ud-din , select a problem which has not been solved or assigned already.

**Comment by developerayuva** [comment]
@lostgirljourney @OctoplusNinja I wish to solve the Candies problem using Java Solution. Please assign it to me.

**Comment by lostgirljourney** [comment]
@developerayuva okay, go ahead. :rocket:

**Comment by Krish03na** [comment]
Please assign me Stable wall in C @lostgirljourney

**Comment by Krish03na** [comment]
@lostgirljourney are you still accepting PRs?

**Comment by lostgirljourney** [comment]
@Krish03na hey go ahead.
