### ISSUE TITLE
Solve Round H

### ISSUE THREAD

**Issue by lostgirljourney** [BlankCoders/GoogleKickStart2020_Solutions#93]
### Solve Questions of Round H

Languages accepted:
 - C
 - C++
 - Java
 - Python

Questions to view: <https://github.com/BlankCoders/GoogleKickStart2020_Solutions/blob/master/Round%20H/QuestionsList.md>

**Important: Comment below to let us know what you want to solve & in which language. 😄**

Assignees:
* Retype ✅
  - C - @imsushant12
  - C++ - @rk1091
  - Java - @sid-khuntwal
  - Python - @drishtantR1508

* Boring Number
  - C - @affanrahman0 
  - C++ - @rk1091 - **Completed**
  - Java - @imsushant12 - **Completed**
  - Python - @shiningflutes - **Completed**

* Rugby
  - C - NA
  - C++ - @rk1091 - **Completed**
  - Java - @7shivamx - **Completed**
  - Python - @drishtantR1508 - **Completed**

* Friends
  - C - NA
  - C++ - @rk1091 - **Completed**
  - Java - @7shivamx  - **Completed**
  - Python - @seanjunheng2  - **Completed**

**NA  - Not Assigned**

🚀 Happy Coding 🚀

**Comment by AlwaysLearning55** [comment]
Hi.

I would like to be assigned the Boring Number in C++;

**Comment by rk1091** [comment]
Hi! 
Will contributions made now be considered for Hacktoberfest 2021? 
If so pls assign Retype in C++, Boring Number in C++, Rugby in C++, and Friends in C++ to me!

**Comment by Dipti821** [comment]
hello @lostgirljourney  I would like to provide the solution of retype and boring number in C++. Please assign this task to me.

**Comment by lostgirljourney** [comment]
@rk1091 hi, yes it will be considered for Hacktoberfest 2021.
@Dipti821 and @rk1091 since both of you have asked 2 questions assignments in the same language; will it be fine if I assign @Dipti821 retype and boring number in C++ and @rk1091 Rugby in C++, and Friends in C++???
Lemme know...

**Comment by rk1091** [comment]
All due respect @lostgirljourney I believe it should be on first come first serve basis and since I asked first, you should assign them to me.

**Comment by lostgirljourney** [comment]
> All due respect @lostgirljourney I believe it should be on first come first serve basis and since I asked first, you should assign them to me. 

Fine @rk1091 assigning you all in C++. 😁

**Comment by rk1091** [comment]
Thanks :)

**Comment by lostgirljourney** [comment]
@Dipti821 can you do in C??

**Comment by Dipti821** [comment]
No.

**Comment by lostgirljourney** [comment]
Fine @Dipti821 you can check other issues.

**Comment by Dipti821** [comment]
ok🙁

**Comment by rk1091** [comment]
Hi, @lostgirljourney. 
Kindly check and merge my pull request for 'Friends' in C++ under completion of Hacktoberfest 2021. 

(Pls approve so that I can proceed with raising pull requests for the other questions as well)

**Comment by rk1091** [comment]
Hi, @lostgirljourney.
Kindly check and merge my pull request for 'Rugby' in C++ under completion of Hacktoberfest 2021.

Also, I just checked my Hacktoberfest profile; under contributions, it says 'Matures in 14days' for the previous merged PR. Would you please tell me what that means? 

(Does it require an approval request from your/backside or just that I need to wait for 14days?)

**Comment by rk1091** [comment]
Hi, @lostgirljourney and @OctoplusNinja 
Kindly check and merge my pull request for 'Retype' in C++ under completion of Hacktoberfest 2021.

**Comment by OctoplusNinja** [comment]
Hi @rk1091, I've merged your PRs and about the Maturing Part, you'll just have to wait for 14days for your PRs to be counted as Hacktoberfest Contributions.

**Comment by rk1091** [comment]
Hi, @lostgirljourney and @OctoplusNinja
Kindly check and merge my pull request for 'Boring Number' in C++ under completion of Hacktoberfest 2021.

Thanks :)

**Comment by sid-khuntwal** [comment]
Hey please assing retype question to me.

**Comment by OctoplusNinja** [comment]
Assigned you @sid-khuntwal

**Comment by sid-khuntwal** [comment]
I have added the required solution please have a look

**Comment by imsushant12** [comment]
Hey, I want to work on Boring-Number in Java

**Comment by lostgirljourney** [comment]
@imsushant12 assigning you

**Comment by drishtantR1508** [comment]
i would like to do retype problem in python

@lostgirljourney @OctoplusNinja

**Comment by drishtantR1508** [comment]
Allow me to to do rugby problem in python

@lostgirljourney @OctoplusNinja

**Comment by lostgirljourney** [comment]
@drishtantR1508 @7shivamx assigned. 🚀

**Comment by lostgirljourney** [comment]
@imsushant12 assigned 🚀

**Comment by shiningflutes** [comment]
Hi would like to do boring numbers in python.

**Comment by seanjunheng2** [comment]
HI I would like to do friends in python!

**Comment by lostgirljourney** [comment]
> HI I would like to do friends in python!
> 

Assigned @seanjunheng2 🚀

**Comment by lostgirljourney** [comment]
@drishtantR1508 hey, you did two commits and did the pr that's why only single pr is showing up on hacktoberfest website. I suggest you to complete single assignment first, let it get merged and then commit other assignment and pr again. 😄

**Comment by drishtantR1508** [comment]
Yeah, actually I created a pr after doing retype problem but then I solved and committed my rugby problem before the first one gets merged, I will keep that in mind for future 😅

**Comment by lostgirljourney** [comment]
@affanrahman0 yes assigned.

**Comment by lostgirljourney** [comment]
Hey @AryaGokhale, that part is assigned and done already, please check other issues/challenges that are marked **NA**.
